spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviematcher
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
aws:
  sns:
    topic-arn: arn:aws:sns:us-east-1:123456789012:MovieMatcherNotifications
    region: us-east-1