apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: movie-matcher-cluster3
  region: us-east-1

vpc:
  id: vpc-0ee08b6d2be505c14 
  subnets:
    public:
      us-east-1a:
        id: subnet-08a19f5b3909e943b
      us-east-1c:
        id: subnet-0989a8ef513a55d5c
      us-east-1b:
        id: subnet-097a6702b863ac26c

nodeGroups:
  - name: movie-matcher-nodes3
    instanceType: t3.small
    desiredCapacity: 
    minSize: 1
    maxSize: 2