FROM gradle:7.5.1-amazoncorretto-21 as build

WORKDIR /home/gradle

COPY --chown=gradle:gradle . .

RUN gradle clean build

FROM amazoncorretto:21 as runtime

COPY --from=build /home/gradle/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]