AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for DynamoDB Table.

Resources:
  QueryDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cqrs-query-table
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref QueryDynamoDBTable