AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for DynamoDB table with indexes for Movie.

Resources:
  MovieTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: movies
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S 
        - AttributeName: genre
          AttributeType: S 
        - AttributeName: releaseYear
          AttributeType: N 
      KeySchema:
        - AttributeName: id
          KeyType: HASH 
      GlobalSecondaryIndexes:
        - IndexName: GenreIndex
          KeySchema:
            - AttributeName: genre
              KeyType: HASH 
          Projection:
            ProjectionType: ALL 
        - IndexName: ReleaseYearIndex
          KeySchema:
            - AttributeName: releaseYear
              KeyType: HASH 
          Projection:
            ProjectionType: ALL 
      BillingMode: PAY_PER_REQUEST 
      Tags:
        - Key: Environment
          Value: Production

Outputs:
  MovieTableName:
    Description: Name of the DynamoDB table
    Value: !Ref MovieTable
  GenreIndexName:
    Description: Name of the GSI for genre
    Value: GenreIndex
  ReleaseYearIndexName:
    Description: Name of the GSI for releaseYear
    Value: ReleaseYearIndex