AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for SNS and a single SQS queue for CQRS pattern.

Resources:
  MovieEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MovieEventsTopic

  MovieEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MovieEventsQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 1209600 

  MovieEventsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref MovieEventsTopic
      Protocol: sqs
      Endpoint: !GetAtt MovieEventsQueue.Arn
      RawMessageDelivery: true

  MovieEventsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MovieEventsQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "SQS:SendMessage"
            Resource: !GetAtt MovieEventsQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref MovieEventsTopic

Outputs:
  MovieEventsTopicArn:
    Description: ARN of the SNS Topic for movie events
    Value: !Ref MovieEventsTopic

  MovieEventsQueueUrl:
    Description: URL of the SQS Queue for all movie events
    Value: !Ref MovieEventsQueue

  MovieEventsQueueArn:
    Description: ARN of the SQS Queue for all movie events
    Value: !GetAtt MovieEventsQueue.Arn